services:
  db:
    image: mariadb:11
    # ports:
    #   - "3307:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ludoplanet
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command: --wait_timeout=28800 --interactive_timeout=28800 --max_allowed_packet=64M
    networks:
      - dokploy-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3503:4173"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3502:8000"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db
    networks:
      - dokploy-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - dokploy-network  
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "2525:1025"
      - "8025:8025"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
